[project]
name = "ncm-transfer"
version = "0.1.0"
description = "网易云音乐NCM文件转换器 - 使用PySide6的GUI应用"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "PySide6>=6.0.0",
    "ncmdump>=0.1.0",
]

[tool.uv]
dev-dependencies = [
    "pyinstaller>=6.0.0",
]
